<a href="https://colab.research.google.com/github/pauarmentaa/Regresion-No-Lineal-y-Regresion-Logistica/blob/main/a%C3%B1o2022_act7_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Cargamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
#Cargar archivo csv desde seaborn
df=pd.read_csv("Gastos_costos_2022.csv")
df.head(5)

,Unnamed: 0,FECHA,FOLIO,PROVEEDOR,DESCRIPCION,TIPO_GASTO,IMPORTE,IVA,TOTAL MX
0,4,2022-01-01,280109,BEPENSA LEASING S.A. DE C.V.,AA RENTA EXIGIBLE CL0000006877 18/36 de 03/12/...,ARRENDAMIENTO FINANCIERO,5551.98,888.32,6440.3
1,5,2022-01-01,007817297284,"BANCO NACIONAL DE MEXICO, S.A.",Servicios de Facturación,COMISION BANCARIA,0.00,0.00,0.0
2,6,2022-01-01,5595,CARLOS ENRIQUE ZERMEÑO GUTIERREZ,Pago,COMPRAS,0.00,0.00,0.0
3,7,2022-01-01,5614,CARLOS ENRIQUE ZERMEÑO GUTIERREZ,Pago,COMPRAS,0.00,0.00,0.0
4,8,2022-01-01,42862,"AESA ARTICULOS ELECTRICOS, S.A. DE C.V.",Pago,COMPRAS,0.00,0.00,0.0

In [ ]:
#Verificar los valores sin repetirse de una columna
unico = np.unique(df['TIPO_GASTO'])
unico

array(['ALIMENTOS', 'ANTICIPO ', 'ANTICIPO COMPRA AUTO',
       'ARRENDAMIENTO FINANCIERO', 'ARRENDAMIENTO LOCAL', 'CALIBRACIONES',
       'CAPACITACION', 'CASETAS', 'COMISION BANCARIA', 'COMISION MIXTA',
       'COMPRA AUTO ', 'COMPRAS', 'COMPRAS ', 'CREDITO ', 'DERECHOS',
       'ENERGIA ELECTRICA', 'FLETE', 'GASOLINA', 'GASTOS IMPORTACION ',
       'GERENCIA ADMON', 'HONORARIOS CONTABLES', 'HONORARIOS JURIDICOS',
       'HONORARIOS PM', 'HOSPEDAJE', 'IMSS/INFONAVIT',
       'INSTALACION ELECTRICA', 'MAQUILAS', 'MAQUINARIA', 'MEDICOS',
       'MENSAJERIA', 'MONITOREO CAMARAS ADT', 'MTTO COMPUTO',
       'MTTO EQUIPO COMPUTO', 'MTTO LOCAL', 'MTTO MAQUINARIA',
       'MTTO OFICINA ', 'MTTO TRANSPORTE', 'NO DEDUCIBLE', 'PAPELERIA',
       'PAQUETERIA', 'PEAJES', 'PUBLICIDAD', 'RENTA AUTO',
       'RENTA COPIADORA', 'SANITIZACION', 'SEGUROS', 'SUBCONTRATOS',
       'SUELDOS DIRECCION', 'SUSCRIPCIONES', 'TELEFONO', 'TRANSPORTE',
       'UNIFORMES', 'VALES DESPENSA', 'VARIOS'], dtype=object)

In [ ]:
#Convierto una variable a dicotómica 
df['TIPO_GASTO']= df['TIPO_GASTO'].replace(['ALIMENTOS', 'ANTICIPO ', 'ANTICIPO COMPRA AUTO',
       'ARRENDAMIENTO FINANCIERO', 'ARRENDAMIENTO LOCAL', 'CALIBRACIONES',
       'CAPACITACION', 'CASETAS', 'COMISION BANCARIA', 'COMISION MIXTA',
       'COMPRA AUTO ', 'CREDITO ', 'DERECHOS',
       'ENERGIA ELECTRICA', 'FLETE', 'GASOLINA', 'GASTOS IMPORTACION ',
       'GERENCIA ADMON', 'HONORARIOS CONTABLES', 'HONORARIOS JURIDICOS',
       'HONORARIOS PM', 'HOSPEDAJE', 'IMSS/INFONAVIT',
       'INSTALACION ELECTRICA', 'MAQUILAS', 'MAQUINARIA', 'MEDICOS',
       'MENSAJERIA', 'MONITOREO CAMARAS ADT', 'MTTO COMPUTO',
       'MTTO EQUIPO COMPUTO', 'MTTO LOCAL', 'MTTO MAQUINARIA',
       'MTTO OFICINA ', 'MTTO TRANSPORTE', 'NO DEDUCIBLE', 'PAPELERIA',
       'PAQUETERIA', 'PEAJES', 'PUBLICIDAD', 'RENTA AUTO',
       'RENTA COPIADORA', 'SANITIZACION', 'SEGUROS', 'SUBCONTRATOS',
       'SUELDOS DIRECCION', 'SUSCRIPCIONES', 'TELEFONO', 'TRANSPORTE',
       'UNIFORMES', 'VALES DESPENSA', 'VARIOS'], "OTROS GASTOS")
df

,Unnamed: 0,FECHA,FOLIO,PROVEEDOR,DESCRIPCION,TIPO_GASTO,IMPORTE,IVA,TOTAL MX
0,4,2022-01-01,280109,BEPENSA LEASING S.A. DE C.V.,AA RENTA EXIGIBLE CL0000006877 18/36 de 03/12/...,OTROS GASTOS,5551.98,888.32,6440.30
1,5,2022-01-01,007817297284,"BANCO NACIONAL DE MEXICO, S.A.",Servicios de Facturación,OTROS GASTOS,0.00,0.00,0.00
2,6,2022-01-01,5595,CARLOS ENRIQUE ZERMEÑO GUTIERREZ,Pago,COMPRAS,0.00,0.00,0.00
3,7,2022-01-01,5614,CARLOS ENRIQUE ZERMEÑO GUTIERREZ,Pago,COMPRAS,0.00,0.00,0.00
4,8,2022-01-01,42862,"AESA ARTICULOS ELECTRICOS, S.A. DE C.V.",Pago,COMPRAS,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...
2571,2575,2022-12-01,863376,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISIONES E INTERESES,OTROS GASTOS,0.00,0.00,0.00
2572,2576,2022-12-01,1092957089,BANCO MERCANTIL DEL NORTE SA INSTITUCION DE BA...,SERVICIOS BANCARIOS,OTROS GASTOS,17310.30,516.32,17826.62
2573,2577,2022-12-01,4,Aesa Articulos Electricos S.A de C.V,Pago,COMPRAS,0.00,0.00,0.00
2574,2578,2022-12-01,16,AESA ARTICULOS ELECTRICOS,Pago,COMPRAS,0.00,0.00,0.00
2575,2579,2022-12-01,17,AESA ARTICULOS ELECTRICOS,Pago,COMPRAS,0.00,0.00,0.00

In [ ]:
#Convierto una variable a dicotómica 
df['TIPO_GASTO']= df['TIPO_GASTO'].replace(['COMPRAS '], "COMPRAS")
df

,Unnamed: 0,FECHA,FOLIO,PROVEEDOR,DESCRIPCION,TIPO_GASTO,IMPORTE,IVA,TOTAL MX
0,4,2022-01-01,280109,BEPENSA LEASING S.A. DE C.V.,AA RENTA EXIGIBLE CL0000006877 18/36 de 03/12/...,OTROS GASTOS,5551.98,888.32,6440.30
1,5,2022-01-01,007817297284,"BANCO NACIONAL DE MEXICO, S.A.",Servicios de Facturación,OTROS GASTOS,0.00,0.00,0.00
2,6,2022-01-01,5595,CARLOS ENRIQUE ZERMEÑO GUTIERREZ,Pago,COMPRAS,0.00,0.00,0.00
3,7,2022-01-01,5614,CARLOS ENRIQUE ZERMEÑO GUTIERREZ,Pago,COMPRAS,0.00,0.00,0.00
4,8,2022-01-01,42862,"AESA ARTICULOS ELECTRICOS, S.A. DE C.V.",Pago,COMPRAS,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...
2571,2575,2022-12-01,863376,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISIONES E INTERESES,OTROS GASTOS,0.00,0.00,0.00
2572,2576,2022-12-01,1092957089,BANCO MERCANTIL DEL NORTE SA INSTITUCION DE BA...,SERVICIOS BANCARIOS,OTROS GASTOS,17310.30,516.32,17826.62
2573,2577,2022-12-01,4,Aesa Articulos Electricos S.A de C.V,Pago,COMPRAS,0.00,0.00,0.00
2574,2578,2022-12-01,16,AESA ARTICULOS ELECTRICOS,Pago,COMPRAS,0.00,0.00,0.00
2575,2579,2022-12-01,17,AESA ARTICULOS ELECTRICOS,Pago,COMPRAS,0.00,0.00,0.00

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df[['TOTAL MX']]
Var_Dep= df['TIPO_GASTO']

In [ ]:
#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

In [ ]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [ ]:
#Se escalan todos los datos
escalar = StandardScaler()

In [ ]:
#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [ ]:
#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

In [ ]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[  2 362]
 [  5 404]]

In [ ]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="weighted", pos_label="COMPRAS")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.4135999918935077

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to 'COMPRAS') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(

In [ ]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.5252263906856404

In [ ]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="weighted", pos_label="COMPRAS")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.5252263906856404

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to 'COMPRAS') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(

In [ ]:
# el puntaje F1 que es una combinación entre la precisión y la sensibilidad, para esto importamos f1_score.
#Calculo el Puntaje F1 del modelo
from sklearn.metrics import f1_score

puntajef1 = f1_score(y_test, y_pred, average="weighted", pos_label="COMPRAS")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.3689227610081935

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to 'COMPRAS') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(